sylius_grid:
    grids:
        app_product_scarcity:
            driver:
                name: doctrine/orm
                options:
                    class: "%app.model.product_scarcity.class%"
            fields:
                id:
                    type: string
                    label: sylius.ui.id
                quantity_left:
                    type: string
                    label: app.ui.quantity_left
                product_variant_name:
                    type: string
                    label: sylius.ui.name
                since:
                    type: datetime
                    label: app.ui.since
            filters:
                quantity_left:
                    type: string
                    label: app.ui.quantity_left
                product_variant_name:
                    type: string
                    label: app.ui.product_variant
                since:
                    type: date
                    label: app.ui.since
            actions:
                item:
                   show:
                        type: show
                   delete:
                       type: delete
